services:
  seafile-mc:
    image: ${SEAFILE_IMAGE_NAME:-franchetti/seafile-arm}:${SEAFILE_IMAGE_TAG:-latest}
    environment:
      TZ:
      SERVER_IP: ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
      USE_HTTPS:
      SEAFILE_ADMIN_EMAIL:
      SEAFILE_ADMIN_PASSWORD:
      MYSQL_HOST: ${MARIADB_ALIAS}
      MYSQL_USER:
      MYSQL_USER_PASSWD:
      MYSQL_ROOT_PASSWD: ${MARIADB_ROOT_PASSWORD}
    networks:
      seafile-net:
      traefik-net:
      mail-net:
    volumes:
      - data-vol:/shared/seafile-data
      - seahub-vol:/shared/seahub-data
      - conf-vol:/shared/conf
      - logs-vol:/shared/logs
      - media-vol:/shared/media
    deploy:
      mode: replicated
      replicas: ${SEAFILE_REPLICAS:-1}
      restart_policy:
        delay: ${SEAFILE_RESTART_DELAY:-10s}
      update_config:
        delay: ${SEAFILE_UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}

        traefik.http.routers.seafile-seahub.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.seafile-seahub.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.seafile-seahub.loadbalancer.server.port: ${SEAFILE_SEAHUB_PORT:-8000}
        traefik.http.routers.seafile-seahub.service: seafile-seahub

        traefik.http.routers.seafile-fileserver.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.seafile-fileserver.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && PathPrefix(`/seafhttp/`)
        traefik.http.middlewares.seafhttp-replace.replacepathregex.regex: ^/seafhttp/(.*)
        traefik.http.middlewares.seafhttp-replace.replacepathregex.replacement: /$$1
        traefik.http.routers.seafile-fileserver.middlewares: seafhttp-replace
        traefik.http.services.seafile-fileserver.loadbalancer.server.port: ${SEAFILE_FILESERVER_PORT:-8082}
        traefik.http.routers.seafile-fileserver.service: seafile-fileserver
      resources:
        limits:
          cpus: '${SEAFILE_RESOURCES_LIMITS_CPUS:-2}'
          memory: ${SEAFILE_RESOURCES_LIMITS_MEMORY:-1200M}
        reservations:
          cpus: '${SEAFILE_RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${SEAFILE_RESOURCES_RESERVATIONS_MEMORY:-700M}

  mariadb:
    image: ${MARIADB_IMAGE_NAME:-mariadb}:${MARIADB_IMAGE_TAG:-latest}
    command:
      - --skip-name-resolve
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_INITDB_SKIP_TZINFO:
    networks:
      seafile-net:
        aliases:
          - ${MARIADB_ALIAS}
    volumes:
      - db-vol:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: ${MARIADB_RESTART_DELAY:-5s}
      update_config:
        delay: ${MARIADB_UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${MARIADB_RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${MARIADB_RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${MARIADB_RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${MARIADB_RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  seafile-net:
    name: ${SEAFILE_NET_NAME:-seafile-net}
    driver: ${SEAFILE_NET_DRIVER:-overlay}
    attachable: ${SEAFILE_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    driver: ${MAIL_NET_DRIVER:-overlay}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-seafile-mc-data-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${DATA_VOL_TYPE}
      o: addr=${DATA_VOL_ADDR},${DATA_VOL_OPTS}
      device: ${DATA_VOL_DEVICE:-:/seafile-mc-data-vol/}

  seahub-vol:
    name: ${SEAHUB_VOL_NAME:-seafile-mc-seahub-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${SEAHUB_VOL_DEVICE:-:/seafile-mc-seahub-vol/}

  conf-vol:
    name: ${CONF_VOL_NAME:-seafile-mc-conf-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${CONF_VOL_DEVICE:-:/seafile-mc-conf-vol/}

  logs-vol:
    name: ${LOGS_VOL_NAME:-seafile-mc-logs-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${LOGS_VOL_DEVICE:-:/seafile-mc-logs-vol/}

  media-vol:
    name: ${MEDIA_VOL_NAME:-seafile-mc-media-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${MEDIA_VOL_DEVICE:-:/seafile-mc-media-vol/}

  db-vol:
    name: ${DB_VOL_NAME:-seafile-mc-db-vol}
    driver: ${VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DB_VOL_DEVICE:-:/seafile-mc-db-vol/}
