version: '3.7'

services:
  seafile:
    image: ${IMAGE_NAME:-seafileltd/seafile}:${IMAGE_TAG:-latest}
    environment:
      SEAFILE_SERVER_HOSTNAME:
      SEAFILE_ADMIN_EMAIL:
      SEAFILE_ADMIN_PASSWORD:
      SEAFILE_SERVER_LETSENCRYPT:
    networks:
      traefik-net:
      mail-net:
    volumes:
      - data-vol:/shared/seafile
      - db-vol:/shared/db
      - logs-vol:/shared/logs
    healthcheck:
      test: wget --spider -nv http://localhost
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-15s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.http.routers.seafile.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.seafile.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.seafile.rule: Host(`${SEAFILE_SERVER_HOSTNAME}`)
        traefik.http.services.seafile.loadbalancer.server.port: ${PORT:-80}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-2}'
          memory: ${RESOURCES_LIMITS_MEMORY:-384M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-200M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-seafile-data-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE:-nfs}
      o: ${DATA_VOL_OPTIONS}
      device: ${DATA_VOL_DEVICE:-:/seafile-data-vol/}

  db-vol:
    name: ${DB_VOL_NAME:-seafile-db-vol}
    driver: local
    driver_opts:
      type: ${DB_VOL_TYPE:-nfs}
      o: ${DB_VOL_OPTIONS}
      device: ${DB_VOL_DEVICE:-:/seafile-db-vol/}

  logs-vol:
    name: ${LOGS_VOL_NAME:-seafile-logs-vol}
