version: '3.7'

services:
  seafile:
    image: ${IMAGE_NAME:-seafileltd/seafile}:${IMAGE_TAG:-latest}
    environment:
      - SEAFILE_SERVER_HOSTNAME
      - SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD
      - SEAFILE_SERVER_LETSENCRYPT
    networks:
      - traefik-net
      - mail-net
    volumes:
      - data-vol:/shared/seafile
      - db-vol:/shared/db
      - logs-vol:/shared/logs
    healthcheck:
      test: wget --spider -nv -t 3 http://localhost
      interval: ${SEAFILE_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${SEAFILE_HEALTHCHECK_TIMEOUT:-1m}
      retries: ${SEAFILE_HEALTHCHECK_RETRIES:-3}
      start_period: ${SEAFILE_HEALTHCHECK_START_PERIOD:-1m}
    deploy:
      mode: replicated
      replicas: ${SEAFILE_REPLICAS:-1}
      labels:
        traefik.frontend.rule: Host:${SEAFILE_SERVER_HOSTNAME}
        traefik.backend: seafile
        traefik.port: '80'
      restart_policy:
        delay: ${SEAFILE_RESTART_POLICY_DELAY:-10s}
        window: ${SEAFILE_RESTART_POLICY_WINDOW:-1m}
      resources:
        limits:
          cpus: "${SEAFILE_LIMITS_CPUS:-2}"
          memory: ${SEAFILE_LIMITS_MEMORY:-384M}
        reservations:
          memory: ${SEAFILE_RESERVATIONS_MEMORY:-200M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    external: true

volumes:
  data-vol:
    name: ${SEAFILE_DATA_VOL_NAME:-seafile-data-vol}
    driver: local
    driver_opts:
      type: ${SEAFILE_DATA_VOLUME_TYPE}
      o: ${SEAFILE_DATA_VOLUME_OPTIONS}
      device: ${SEAFILE_DATA_VOLUME_DEVICE}

  db-vol:
    name: ${SEAFILE_DB_VOL_NAME:-seafile-db-vol}

  logs-vol:
    name: ${SEAFILE_LOGS_VOL_NAME:-seafile-logs-vol}
